---
title: "jw_a1_task1"
author: "Joe Walderman"
date: "1/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(lubridate)
library(patchwork)
```

## Reading in data and wrangling

```{r readxl, echo=TRUE, eval=TRUE, warning=FALSE}
amphib <- read_excel(here("data", "sierra_amphibians.xlsx") ) %>% 
  clean_names() %>% 
  drop_na() %>% 
  mutate(across(where(is.character), tolower)) %>% # convert all characters to lowercase
  mutate(date = ymd(survey_date)) %>%
  mutate(year = year(date))

amphib_count <- amphib %>% 
  filter(amphibian_life_stage != "eggmass") %>% 
  group_by(year, amphibian_life_stage) %>%
  summarise(count = n())

amphib_old <- amphib %>% 
  filter(amphibian_life_stage %in% c("adult", "subadult")) %>% 
  count(lake_id) %>% 
  slice_max(n, n = 5) %>% 
  arrange(-n)

amphib_old$lake_id <- as.character(amphib_old$lake_id) #converting from numeric to character for graph aesthetics

graph_a <- ggplot(data = amphib_count, aes(x = year, y = count)) +
  geom_line(aes(color = amphibian_life_stage))

graph_b <- ggplot(data = amphib_old, aes(x = lake_id, y = n)) +
  geom_col() +
  labs(x = "Lake ID",
       y = "Frog Count",
       title = "Adult and Sub-Adult Mountain Yellow-Legged Frogs by Lake")

graph_a / graph_b
```



